---
title: "Gov 50 Final Project"
author: "Chuchu Zhang"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to labor economic policies. Through using available data, I would like to find out if past policies have helped advance the well-being of workers (variable to be specified later on) in the food delivery industry in China. 

A problem with this kind of observational study is there is not really a control group -- in the same region, workers who were never influenced by the policy -- so the counterfactual is not balanced with an observation of the control group. If I use the before-and-after design, do I need to make sure that it was the same group of people whose results we are studying after the policy was implemented? 

Given the unclear definition of independent contractors in China, I may need to start off by giving the subjects an operational definition, such as number of working hours a week on one platform, proportion of income received from one single platform, etc. 